name: Review Dog
on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository Files
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            js:
              - '**/*.js'

      - uses: actions/setup-node@v3
        if: steps.changes.outputs.js == 'true'
        with:
          node-version: 22
          registry-url: https://npm.github.aimdt.com

      - name: Install dependencies
        run: npm install eslint -D
        
      - name: Eslint review
        if: steps.changes.outputs.js == 'true'
        uses: reviewdog/action-eslint@v1.3
        with:
          reporter: github-pr-review
          fail_on_error: true
          level: warning
          filter_mode: file
